[build-system]
requires = ["scikit-build-core>=0.9", "pybind11"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[project]
name = "AutoX"
version = "0.1.0a0"
description = "A framework for ARC to make running and managing multiple processes easier"
readme = "README.md"
requires-python = "==3.10.*"

dependencies = [
    "filterpy>=1.4.5",
    "iceoryx2==0.9.0",
    "matplotlib>=3.7",
    "numpy==1.24.*",
    "opencv-python==4.7.*",
    "pyrealsense2>=2.58.1.10581",
    "pyserial==3.5.*",
    "quik-config>=1.9.1",
    "scalene>=2.2.1",
    "super-map>=1.3.3",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    # docs gen
    "myst-parser>=4.0.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.14.14",
    "sphinx>=8.1.3",
    "sphinx-autodoc-typehints>=3.0.1",
    "sphinx-book-theme>=1.1.4",
    "tqdm>=4.66",
]
[project.optional-dependencies]
gpu = [
    "cupy-cuda12x>=13.6.0",
]

[tool.ruff.lint]
select = [
  "D",   # pydocstyle
  "I", # sort imports
]
ignore = [
    "D105", # no doc string for magic or dunder methods
    "D107", # no doc string for __init__
    "D104", # no doc string for __init__.py
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
    "tensorrt",
    "pycuda.*",
    "pyrealsense2",
    "ultralytics.*",
    "onnx",
    "calibrator",
    "file_system_py",
    "cfgv",
    "serial",
    "quik_config",
    "super_map",
    "iceoryx2",
    "iceoryx2.*",
]
ignore_missing_imports = true

[tool.ty.analysis]
# Suppress errors for all jetson packages and compiled CUDA extensions
allowed-unresolved-imports = ["pyrealsense2.**", "pf_cuda_cv", "cupy"]
