#!/usr/bin/env python3
"""Generate stable udev symlinks for the circlet ring cameras.

``/dev/videoN`` numbers are assigned in enumeration order and shuffle across
reboots / replugs (we watched them move during bring-up). That makes the
``circlet.cameras[i].index`` config non-deterministic: ``cam0`` might be a
different physical camera after a reboot.

This script keys each camera on its **USB port path** (e.g. ``1-4.1``), which is
stable as long as the physical wiring doesn't change, and emits a udev rule that
creates a fixed ``/dev/circlet/camN`` symlink for it. Cameras are numbered by
sorted port path so the mapping is reproducible; edit the printed rules if you
want a different physical->id assignment.

Usage::

    uv run utils/circlet_udev.py            # print the rules + the config block
    uv run utils/circlet_udev.py --install  # write to /etc/udev/rules.d + reload

After installing, point the config at the symlinks (device wins over index)::

    cameras:
        - {device: /dev/circlet/cam0, yaw_deg: 0,   translation: [0, 0, 0]}
        ...

Re-run this after you finalize the wiring (adding the 5th cam / moving ports).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

RULES_PATH = Path("/etc/udev/rules.d/99-circlet-cameras.rules")
# Match the ring cameras by their V4L2 device name. Adjust if you mix in a
# different camera model on the same machine.
CAMERA_NAME_MATCH = "Global Shutter"
SYS_V4L = Path("/sys/class/video4linux")


def _read(path: Path) -> str:
    try:
        return path.read_text().strip()
    except OSError:
        return ""


def discover_cameras() -> list[dict]:
    """Return capture nodes for the ring cameras: dev, usb port path, name.

    Only the capture node of each camera is returned (``ATTR{index}==0``); the
    sibling metadata node (index 1) is skipped so each physical camera yields one
    entry.
    """
    cams: list[dict] = []
    for vdir in sorted(SYS_V4L.glob("video*")):
        name = _read(vdir / "name")
        if CAMERA_NAME_MATCH not in name:
            continue
        if _read(vdir / "index") != "0":  # capture node only, not metadata
            continue
        # Resolve the owning USB interface, then walk up to the device whose name
        # is the port path (e.g. ".../usb1/1-4/1-4.1/1-4.1:1.0/video4linux/videoN").
        dev_link = (vdir / "device").resolve()
        port = None
        for parent in [dev_link, *dev_link.parents]:
            base = parent.name
            # USB port path looks like "1-4.1" (root-bus-port[.port...]); the
            # interface dir is "1-4.1:1.0" -- take the part before the colon.
            core = base.split(":", 1)[0]
            if core and core[0].isdigit() and "-" in core:
                port = core
                break
        if port is None:
            continue
        cams.append({"dev": f"/dev/{vdir.name}", "port": port, "name": name})
    # Deterministic id assignment by port path.
    cams.sort(key=lambda c: c["port"])
    for i, c in enumerate(cams):
        c["id"] = i
    return cams


def render_rules(cams: list[dict]) -> str:
    """Render the udev rules file content for the discovered cameras."""
    lines = [
        "# Stable circlet camera symlinks -- generated by utils/circlet_udev.py",
        "# Keyed on USB port path (KERNELS); survives /dev/videoN renumbering.",
        "# ATTR{index}==0 selects the capture node (not the metadata sibling).",
    ]
    for c in cams:
        lines.append(
            f'SUBSYSTEM=="video4linux", KERNELS=="{c["port"]}", '
            f'ATTR{{index}}=="0", SYMLINK+="circlet/cam{c["id"]}"'
        )
    return "\n".join(lines) + "\n"


def render_config_block(cams: list[dict]) -> str:
    """Render a ready-to-paste circlet ``cameras:`` YAML block using the symlinks."""
    yaws = [0, 90, 180, 270]
    lines = ["                cameras:"]
    for c in cams:
        yaw = yaws[c["id"]] if c["id"] < len(yaws) else 0
        lines.append(
            f"                    - {{device: /dev/circlet/cam{c['id']}, "
            f"yaw_deg: {yaw}, translation: [0, 0, 0]}}"
        )
    return "\n".join(lines)


def install(rules: str) -> None:
    """Write the rules file and reload udev (needs root; uses sudo)."""
    try:
        subprocess.run(
            ["sudo", "tee", str(RULES_PATH)],
            input=rules.encode(),
            check=True,
            stdout=subprocess.DEVNULL,
        )
        subprocess.run(["sudo", "udevadm", "control", "--reload-rules"], check=True)
        subprocess.run(["sudo", "udevadm", "trigger"], check=True)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        sys.exit(f"install failed: {e}")
    print(f"installed -> {RULES_PATH}; symlinks appear under /dev/circlet/")


def main() -> None:
    """Discover cameras, print rules + config block, optionally install."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--install",
        action="store_true",
        help="write the rules to /etc/udev/rules.d and reload udev (uses sudo)",
    )
    args = ap.parse_args()

    cams = discover_cameras()
    if not cams:
        sys.exit(
            f"no cameras matching {CAMERA_NAME_MATCH!r} found under {SYS_V4L}. "
            "Are they plugged in? Adjust CAMERA_NAME_MATCH if the model differs."
        )

    print(f"# discovered {len(cams)} camera(s):")
    for c in cams:
        print(f"#   cam{c['id']}: port {c['port']:8s} {c['dev']}  ({c['name']})")
    print()
    rules = render_rules(cams)
    print(rules)
    print("# paste into src/info.yaml under circlet: (device wins over index)")
    print(render_config_block(cams))

    if args.install:
        print()
        install(rules)


if __name__ == "__main__":
    main()
