/**
 * @file armor.h
 * @brief Auto-generated header for armor.cpp
 *
 * Generated by Header File Generator on 2026-05-20.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef ARMOR_H
#define ARMOR_H

/* ─── Includes ────────────────────────────────────────────────────────── */

#include <math.h>
#include <vector>
#include <utility>
#include "types.h"
#include <cmath>
#include <algorithm>
#include <opencv2/imgproc.hpp>

std::vector<std::pair<Light, Light>> pair_lights(const std::vector<Light>& lights);
std::vector<Light> detect_lights(const std::vector<std::vector<cv::Point>>& contours);
std::vector<Panel> define_panels (std::vector<std::pair<Light, Light>> light_pairs);

#endif /* ARMOR_H */
