/**
 * @file frame_process.h
 * @brief Auto-generated header for frame_process.cpp
 *
 * Generated by Header File Generator on 2026-05-22.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef FRAME_PROCESS_H
#define FRAME_PROCESS_H

/* ─── Includes ────────────────────────────────────────────────────────── */

#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>

cv::Mat numpy_to_mat(pybind11::array_t<uint8_t>& arr);

std::vector<std::vector<cv::Point>> process_frame(cv::Mat frame, char color);


#endif /* FRAME_PROCESS_H */
