/**
 * @file icon_detection.h
 * @brief Auto-generated header for icon_detection.cpp
 *
 * Generated by Header File Generator on 2026-05-20.
 * DO NOT EDIT — re-run the generator to update.
 */

#ifndef ICON_DETECTION_H
#define ICON_DETECTION_H

#include <opencv4/opencv2/opencv.hpp>

#include "types.h"
#include "armor.h"

void load_icons();
void set_icon_tolerance(float tol);
void icon_detection(const cv::Mat& input_image, std::vector<Panel>& panels);


#endif /* ICON_DETECTION_H */
